/**
 *
 * $Id$
 */
package mvc.validation;

import mvc.Action;
import mvc.Model;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mvc.View}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateActions(EList<Action> value);
	boolean validateModel(Model value);
}
